#!/usr/bin/env python3
"""Generate the weed_field Gazebo model: oversized magenta weed blobs.

Weeds are deliberately unrealistic — large flat magenta cylinders scattered
over the surveyed 80x80 m area — so the drones' OpenCV pipeline has an
unambiguous, tunable detection target (HSV band in camera_processor.py).

Output is a single static, visual-only model at src/custom_gz/models/weed_field
(included by swarm_drone.sdf and swarm_drone_spray.sdf) plus ground_truth.json
with each weed's Gazebo x/y and derived lat/lon for checking detections.

Regenerate with a different layout:
    python3 src/custom_gz/worlds/generate_weeds.py --count 20 --seed 7
"""
import argparse
import json
import math
import os
import random

# Must match LAT_BASE/LON_BASE in src/scripts/start_drone_container.sh and
# FIELD_ORIGIN_LAT/LON in compose_decentralized.launch.py. The field origin
# corresponds to Gazebo (45, 50) — drone 0's spawn/home.
LAT_BASE = 40.072842
LON_BASE = -105.230575
METERS_PER_DEG_LAT = 111111.0

DIAMETER_MIN = 1.2
DIAMETER_MAX = 2.5
BLOB_HEIGHT = 0.2
BLOB_Z = 0.2  # field surface tops out at z=0.1; blob center 0.2 -> spans 0.1..0.3


def gazebo_to_latlon(x, y, center_x, center_y):
    """Map Gazebo world x/y to lat/lon, with (center_x, center_y) = field origin."""
    north = y - center_y
    east = x - center_x
    lat = LAT_BASE + north / METERS_PER_DEG_LAT
    lon = LON_BASE + east / (METERS_PER_DEG_LAT * math.cos(math.radians(LAT_BASE)))
    return lat, lon


def generate_weeds(count, seed, center, area):
    rng = random.Random(seed)
    half = area / 2.0
    weeds = []
    for i in range(count):
        x = round(rng.uniform(center[0] - half, center[0] + half), 3)
        y = round(rng.uniform(center[1] - half, center[1] + half), 3)
        diameter = round(rng.uniform(DIAMETER_MIN, DIAMETER_MAX), 3)
        lat, lon = gazebo_to_latlon(x, y, center[0], center[1])
        weeds.append({
            "id": i, "x": x, "y": y, "diameter": diameter,
            "lat": round(lat, 8), "lon": round(lon, 8),
        })
    return weeds


def _weed_link(w):
    return f"""    <link name="weed_{w['id']}">
      <pose>{w['x']} {w['y']} {BLOB_Z} 0 0 0</pose>
      <visual name="visual">
        <geometry>
          <cylinder>
            <radius>{w['diameter'] / 2.0}</radius>
            <length>{BLOB_HEIGHT}</length>
          </cylinder>
        </geometry>
        <material>
          <ambient>1 0 1 1</ambient>
          <diffuse>1 0 1 1</diffuse>
          <emissive>1 0 1 1</emissive>
        </material>
      </visual>
    </link>
"""


def model_sdf(weeds):
    links = "".join(_weed_link(w) for w in weeds)
    return f"""<?xml version="1.0"?>
<sdf version="1.9">
  <!-- GENERATED by src/custom_gz/worlds/generate_weeds.py - do not hand-edit.
       Oversized magenta weed blobs for OpenCV detection testing. Visual-only
       (no collision) so they can never interfere with flight. Ground truth
       positions: ground_truth.json next to this file. -->
  <model name="weed_field">
    <static>true</static>
{links}  </model>
</sdf>
"""


MODEL_CONFIG = """<?xml version="1.0"?>
<model>
  <name>weed_field</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <author>
    <name>Yahia Aly</name>
    <email>yahia@ezrpa.com</email>
  </author>
  <description>
    Generated magenta weed blobs over the surveyed field area - detection
    targets for the drones' OpenCV camera pipeline. See generate_weeds.py.
  </description>
</model>
"""


def write_model(weeds, out_dir, meta):
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "model.sdf"), "w") as f:
        f.write(model_sdf(weeds))
    with open(os.path.join(out_dir, "model.config"), "w") as f:
        f.write(MODEL_CONFIG)
    with open(os.path.join(out_dir, "ground_truth.json"), "w") as f:
        json.dump({**meta, "weeds": weeds}, f, indent=2)


def main():
    default_out = os.path.normpath(os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "models", "weed_field"))
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--count", type=int, default=12)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--center", type=float, nargs=2, default=[45.0, 50.0],
                   metavar=("X", "Y"), help="Gazebo x/y of the field origin")
    p.add_argument("--area", type=float, default=80.0, help="side of the square area (m)")
    p.add_argument("--out", default=default_out)
    args = p.parse_args()

    weeds = generate_weeds(args.count, args.seed, tuple(args.center), args.area)
    write_model(weeds, args.out, {
        "seed": args.seed, "count": args.count,
        "center": args.center, "area": args.area,
    })
    print(f"wrote {len(weeds)} weeds to {args.out}")


if __name__ == "__main__":
    main()
