services:
  swarm_controller:
    build:
      context: ./src/dockerfiles
      dockerfile: Dockerfile.ros2
    container_name: swarm_controller
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - NUM_DRONES=${NUM_DRONES:-4}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./src:/root/ros2_ws/src:cached
      - ./logs:/root/logs:delegated
      - ./src/scripts:/root/scripts:ro
      - ./src/dockerfiles/config:/root/config:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    devices:
      - /dev/dri:/dev/dri
    command: ["/root/scripts/start_swarm_controller.sh"]

  dds_agent:
    build:
      context: ./src/dockerfiles
      dockerfile: Dockerfile.dds-agent
    container_name: dds_agent
    network_mode: host
    restart: unless-stopped
    command: [ "MicroXRCEAgent", "udp4", "-p", "2019", "-v", "6" ]


  # Drone instances with Serial DDS + UDP MAVLink
  drone_1:
    build:
      context: ./src/dockerfiles
      dockerfile: Dockerfile.ardupilot
    network_mode: host
    environment:
      - INSTANCE=0
      - SYSID_THISMAV=1
      - ROS_DOMAIN_ID=10
      - DDS_UDP_PORT=2019
    volumes:
      - ./instance_0:/sitl/instance_0
      - ./config:/config
      - ./src/scripts:/root/scripts:ro
    command: ["/root/scripts/start_drone_container.sh"]
    
  drone_2:
    build:
      context: ./src/dockerfiles
      dockerfile: Dockerfile.ardupilot  
    network_mode: host
    environment:
      - INSTANCE=1
      - SYSID_THISMAV=2
      - ROS_DOMAIN_ID=1
      - DDS_UDP_PORT=2020
    volumes:
      - ./instance_1:/sitl/instance_1
      - ./config:/config
      - ./src/scripts:/root/scripts:ro
    command: ["/root/scripts/start_drone_container.sh"]